# Generated by Django 5.2.9 on 2025-12-31 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Main Account', max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, default=1000000000, max_digits=14)),
            ],
        ),
    ]
