# Generated by Django 5.2.9 on 2025-12-31 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('total_watts', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_watt_hours', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recommended_inverter', models.CharField(max_length=50)),
                ('recommended_battery_count', models.IntegerField()),
                ('recommended_solar_panels', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='load_calculations', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='LoadAppliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('watts', models.IntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('hours_per_day', models.DecimalField(decimal_places=2, max_digits=4)),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appliances', to='load_calculator.loadcalculation')),
            ],
        ),
    ]
