# Generated by Django 5.2.9 on 2025-12-31 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load_calculator', '0001_initial'),
        ('quotations', '0002_alter_quotation_load_calculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadcalculation',
            name='quotation_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quotations.quotation'),
        ),
    ]
