# Generated by Django 5.2.9 on 2025-12-31 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load_calculator', '0002_loadcalculation_quotation_id'),
        ('quotations', '0002_alter_quotation_load_calculation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadcalculation',
            name='quotation_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotations.quotation'),
        ),
    ]
