# Generated by Django 5.2.9 on 2025-12-31 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('load_calculator', '0003_alter_loadcalculation_quotation_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loadcalculation',
            name='quotation_id',
        ),
    ]
