# Generated by Django 5.2.9 on 2026-01-01 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='quotation',
        ),
    ]
