# Generated by Django 5.2.9 on 2026-03-11 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_remove_invoice_quotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='tax_amount',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.IntegerField(max_length=20),
        ),
    ]
