# Generated by Django 5.2.9 on 2026-03-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_alter_invoice_tax_amount_alter_invoice_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='balance_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
