# Generated by Django 5.2.9 on 2026-03-11 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_invoice_balance_due'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='balance_due',
        ),
    ]
