# Generated by Django 5.2.9 on 2025-12-31 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('load_calculator', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_number', models.CharField(max_length=50, unique=True)),
                ('battery_quantity', models.PositiveIntegerField()),
                ('panel_quantity', models.PositiveIntegerField()),
                ('installation_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('converted', 'Converted to Invoice')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('battery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='battery_quotes', to='products.product')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('inverter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inverter_quotes', to='products.product')),
                ('load_calculation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='load_calculator.loadcalculation')),
                ('solar_panel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='panel_quotes', to='products.product')),
            ],
        ),
    ]
