# Generated by Django 5.2.9 on 2025-12-31 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load_calculator', '0001_initial'),
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='load_calculation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quotation', to='load_calculator.loadcalculation'),
        ),
    ]
